taskapp/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  post 'carts/index'
  post 'projects/user_detail'
		resources :projects
                root 'projects#index'

end

taskapp/app/models/blog.rb
class Blog < ActiveRecord::Base
end

taskapp/app/models/click.rb
class Click < ActiveRecord::Base
end

taskapp/app/models/detail_area.rb
# 詳細エリア
class DetailArea < ActiveRecord::Base
  belongs_to :pref
	end

taskapp/app/models/item_desc.rb
class ItemDesc < ActiveRecord::Base
end

taskapp/app/models/item_sell.rb
class ItemSell < ActiveRecord::Base
end

taskapp/app/models/pref.rb
# 県
class Pref < ActiveRecord::Base
  has_many :detail_areas
	end

taskapp/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :reviews
	has_many :user_items
	validates :title,
	presence: { message: "入力してください" },
	length: { minimum: 3, message: "3文字以上必要"}

  def hello
    self.title += "でござる"
  end 

  def price_up
    self.price += 1
  end

  def get_item_code
    self.item_code
  end

  def self.search(search) #self.でクラスメソッドとしている
    if search.blank? # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      all
    else
      Project.where(['title LIKE ?', "%#{search}%"])
      #conditions = %w[content name email site_url].map { |c| "comments.#{c} like :search" }
      #where(conditions.join(" or "), :search => "%#{search}%")
    end
  end
end

taskapp/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :projects
  self.table_name = 'reviews'

  scope :star, ->(star) {where("star >= ?", star) }
  
end

taskapp/app/models/sellbooks.rb
class Sellbooks < ActiveRecord::Base
end

taskapp/app/models/shop.rb
class Shop < ActiveRecord::Base
  
  self.table_name = 'sellbooks'
end

taskapp/app/models/simple_log.rb
class SimpleLog < ActiveRecord::Base
end

taskapp/app/models/store.rb
# 店舗
class Store < ActiveRecord::Base
  belongs_to :pref
	end

taskapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
			 :recoverable, :rememberable, :trackable, :validatable
	has_and_belongs_to_many :roles
def has_role?(name)
	self.roles.where(name: name).length > 0
	end
	end

taskapp/app/models/user_item.rb
class UserItem < ActiveRecord::Base
  belongs_to :reviews
  self.table_name = 'user_items'
end

taskapp/app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController

  def index
    #render plain: params[:user_id].inspect
    
    @ra = Project.joins("LEFT OUTER JOIN reviews ON projects.id = reviews.project_id LEFT OUTER JOIN user_items ON user_items.user_id = reviews.user_id").where("reviews.user_id = ?" , params[:user_id]).select("projects.*, reviews.* , user_items.*")
    
    @r = Project.joins("LEFT OUTER JOIN reviews ON projects.id = reviews.project_id LEFT OUTER JOIN user_items ON user_items.user_id = reviews.user_id").where("reviews.project_id = ?" , params[:id]).select("reviews.* , user_items.*")
  end
  def new
  end
end

taskapp/app/helpers/application_helper.rb
module ApplicationHelper

  def div_tag_if(condition, content_or_options_with_block = nil, options = nil, escape = true, &block)
    # condition が trueの場合だけ、content_tagメソッドでdivタグを作成する
    # falseの場合は、何も作成しない
    if condition
      content_tag("div", content_or_options_with_block, options, escape, &block)
    end
  end
  def add_star
    image_tag("star.jpg", :size => "22x22", :alt => "アイコン")
  end
end

taskapp/app/helpers/carts_helper.rb
module CartsHelper
end

taskapp/app/helpers/home_helper.rb
module HomeHelper
end

taskapp/app/helpers/shop_helper.rb
module ShopHelper
end

taskapp/app/helpers/user_details_helper.rb
module UserDetailsHelper
end

taskapp/app/helpers/users_helper.rb
module UsersHelper
end

taskapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

taskapp/app/views/user_details/index.html.erb
<% require 'pp'%>

<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<meta charset="utf-8">
<title>後期就活ナビ2017</title>
<meta name="description" content="2017年度後半に活動する新卒学生のための就職情報サイト「後期就活ナビ」。2016年6月〜2017年3月で、採用を継続している企業だけを掲載しているので、選考を受けられる企業を見つけやすくなっています。">
<meta name="keywords" content="就職,採用,新卒採用,新卒,就活,後半就活">

<meta property="og:title" content="後期就活ナビ2017" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://koukisyukatunavi.jp/" />
<meta property="og:image" content="https://koukisyukatunavi.jp/assets/img/navi/kouki_ogpimg.png" />
<meta property="og:site_name" content="後期就活ナビ2017" />
<meta property="og:description" content="2017年度後半に活動する新卒学生のための就職情報サイト「後期就活ナビ」。2016年6月〜2017年3月で、採用を継続している企業だけを掲載しているので、選考を受けられる企業を見つけやすくなっています。" />
<meta property="fb:app_id" content="102054676870348" />
<meta name="twitter:card" content="summary">
<link rel="icon" href="https://koukisyukatunavi.jp/assets/img/navi/favicon.png">
<link rel="apple-touch-icon" href="https://koukisyukatunavi.jp/assets/img/navi/apple-touch-icon.png">
<link type="text/css" rel="stylesheet" href="https://koukisyukatunavi.jp/assets/css/bootstrap/bootstrap.min.css?1471537404" />
<link type="text/css" rel="stylesheet" href="https://koukisyukatunavi.jp/assets/css/style.css?1467814606" />
<link type="text/css" rel="stylesheet" href="https://koukisyukatunavi.jp/assets/css/jquery.bxslider.css?1464959907" />
<link type="text/css" rel="stylesheet" href="/assets/css/validationEngine.jquery.css">
<link type="text/css" rel="stylesheet" href="/assets/css/bootstrap-datepicker3.min.css">
</head>
<body>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 880163570;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/880163570/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<header>
<div class="container">
<div class="clearfix">
<div class="pull-left description">これから頑張る！就活生を応援するナビサイト</div>
<div class="pull-right">
<span class="comment"><%= link_to 'トップページへ',projects_path %></span>
<span class="comment"><a href="https://koukisyukatunavi.jp/introduction">採用担当者様へ</a></span>
</div>
</div>
<div class="clearfix">
<div class="pull-left">
<h1 style="margin-top: 0"><a href="https://koukisyukatunavi.jp/"><img alt="後期就活ナビ2017" src="https://koukisyukatunavi.jp/assets/img/navi/base/logo.png?1461649316" /></a></h1>
</div>
<div class="pull-right">
<span class="link_login">
<% if session[:session_id].present? then %>
  こんにちは！ 
<a href="https://koukisyukatunavi.jp/login" class="btn btn-green">

  <% @r.each do |userlist| %>
    <%= userlist.user %>
  <% end %>
  さん
<%=  link_to 'ログアウト' , destroy_user_session_path %>
<% else %>
ログイン
<%=  link_to '会員登録' , new_project_path %>

<% end %>
</a>
</span>
<span>

<% if @notice.present? then %>

<% else %>
<% end %>

</span>
</div>
</div>
</div>
</header>
<div class="top-image">
<div class="container">
<div class="row">
<div class="col-xs-7 top_search">

<% price = 2500 * 1.05 %>

<h2>レビュー</h2></p>
<br>
<% @ra.each do |userlist| %>
  <%= link_to image_tag(userlist.pict_path, :size => "80x80"), project_path(userlist.project_id) %>
  <%= add_star %>
  <%= userlist.star %>
  :
  <%= userlist.created_at.strftime('%Y年%m月%d日 %H:%M') %>
  <%= userlist.review %>
  <br>
  <br>
  <hr>
<% end %>
</p>
</p>
</p>
</ul>
<div class="tab-content">
<div class="base-container tab-pane in active" id="tab_s1">
<div class="col-xs-5">
<p class="top_search_head"><img src="/assets/img/navi/base/arrow01.png">条件を指定して探す</p>
<ul class="search-menu-list">
<li onclick="show_search(1)">業界</li>
<li onclick="show_search(2)">職種</li>
<li onclick="show_search(3)">勤務地</li>
</ul>
<input type="submit" class="btn gobutton" form="search_company" value="">
</div>
<div class="col-xs-7">
<%= form_tag("/search", method: "get") do %>
<p class="top_search_head"><img src="/assets/img/navi/base/arrow01.png">キーワードで探す</p>
<div class="sform_keyword">
<div class="form-group">
<%= text_field_tag(:t) %>
<br>
<%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "トイレ・風呂別") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "オートロック") %>
</div>
<div class="form-group">
<input type="hidden" name="type" value="0">
<input type="submit" class="btn gobutton" value="">
</div>
</div>
<% end %>


</div>
</div>
<div class="base-container tab-pane" id="tab_s2">
<div class="col-xs-5">
<p class="top_search_head"><img src="/assets/img/navi/base/arrow01.png">条件を指定して探す</p>
<ul class="search-menu-list">
<li onclick="show_esearch(1)">開催日</li>
<li onclick="show_esearch(2)">業種</li>
<li onclick="show_esearch(3)">開催地</li>
</ul>
<input type="submit" class="btn gobutton" form="search_event" value="">
</div>
<div class="col-xs-7 top_s_event_right">
<a href="https://koukisyukatunavi.jp/searchevent"><img src="https://koukisyukatunavi.jp/assets/img/navi/base/go2.png?1461649315" alt="" /></a>
</div>
</div>
</div>
</div>
<div class="col-xs-5">

<br>
<div class="top-newcompany-image">
<ul class="bxslider">
<li>
<a href="https://koukisyukatunavi.jp/searchcompany/company/1637">
<img src="/assets/img/navi/company/f9b5f95419903539115fa907d3b8c0ae.jpg">
<div class="top-newcompany-body">
<p class="company_name" style="line-height:1.2;">株式会社セントメディア</p>
<p class="company_copy" style="line-height:1.4;">Believe in your possibility！～根拠なき自信～</p>
</div>
</a>
</li>
<li>
<a href="https://koukisyukatunavi.jp/searchcompany/company/1635">
<img src="/assets/img/navi/company/6e78442d61de67f2792f3b3b1bb909f6.jpg">
<div class="top-newcompany-body">
<p class="company_name" style="line-height:1.2;">アイズテクノロジー株式会社</p>
<p class="company_copy" style="line-height:1.4;">私たちと日本の健康のため、そして笑顔のために仕事をしませんか？</p>
</div>
</a>
</li>
<li>
<a href="https://koukisyukatunavi.jp/searchcompany/company/1634">
<img src="/assets/img/navi/company/93f6fc433963fbdfff77a605a9c0da4f.jpg">
<div class="top-newcompany-body">
<p class="company_name" style="line-height:1.2;">株式会社インタートレード</p>
<p class="company_copy" style="line-height:1.4;">他社の真似はしない。自分たちオリジナルのビジネスで勝負する！！</p>
</div>
</a>
</li>
</ul>
</div>
</div>
</div>
<hr>
<br>

</div>
</div>

taskapp/app/views/user_details/new.html.erb
<h1>UserDetails#new</h1>
<p>Find me in app/views/user_details/new.html.erb</p>